351_Общие правки по верстке
mihan007/ldg_v2 pull request #34
Opened 2020-08-31 14:12 UTC by nelmare

https://paradox.myjetbrains.com/youtrack/issue/LDG-351

2020-08-31 16:20 UTC, mihan007 requested changes

2020-08-31 16:20 UTC, mihan007 commented on resources/sass/common.scss
> +//.fa-building,
мертвый код

2020-08-31 16:20 UTC, mihan007 commented on resources/views/includes/header-app.blade.php
> +{{--                    <i class="fa fa-building mr-2" aria-hidden="true"></i>--}}
мертвый код

2020-09-01 08:55 UTC, nelmare commented on resources/sass/common.scss
> +//.fa-building,
почистила

2020-09-07 13:52 UTC, merged